name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 2.6
        uses: actions/setup-ruby@v1
        with:
          python-version: '2.6'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build html
        run: |
          jekyll build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy
        run: |
          curl -X POST https://api.github.com/repos/cloudmitigator/reflex-www-infrastructure/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token $GITHUB_PAT" \
          --data '{"event_type": "deploy"}'
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
